runs:
  using: "composite"
  steps:
  - name: Setup MySQL Tuner repository
    uses: actions/checkout@v3

  - name: Set up MySQL
    uses: mirromutth/mysql-action@v1.1
    with:
      mysql root password: "root"
      mysql version: "${{ inputs.MYSQL_VERSION }}"