runs:
  using: "composite"
  steps:
    - name: Setup MySQL Tuner repository
      uses: actions/checkout@v3

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: "root"
        mysql version: "${{ inputs.MYSQL_VERSION }}"

    - name: Injecting credentials
      run: |
        echo -e "[client]\nuser=root\npassword=root\nhost=127.0.0.1\nprotocol=TCP" > $HOME/.my.cnf

    - name: Cloning test_db dataset
      run: |
        git clone https://github.com/datacharmer/test_db.git

    - name: Injecting test_db dataset
      run: |
        sleep 5s
        cd test_db
        netstat -ltpn
        mysql -e 'select version();'
        mysql -e 'CREATE DATABASE data;'
        mysql data< ./employees.sql
        cd -
        rm -rf test_db