# This is a basic workflow to help you get started with Actions

name: Test with databases

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: .github/actions/install_db
        with:
          MYSQL_VERSION: "8.0"

      # Runs a single command using the runners shell
      - name: Run help mode
        run: perl ./mysqltuner.pl --help

      # Runs a single command using the runners shell
      - name: Run verbose mode
        run: sudo perl ./mysqltuner.pl --user=root --pass=root --protocol tcp --verbose
